version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5433:3306'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: alumni
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '8543:8543'     
