# docker-compose.yml
version: '3'
services:
    app:
        build: .
        depends_on:
            - postgres
        ports:
            - '3000:3000'
        volumes:
            - .:/app/
            - /app/node_modules

    postgres:
        image: postgres:alpine
        ports:
            - '35432:5432'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
